"""Esquema inicial de Kipu Knowledge (todas las tablas de la sección 7 del diseño).

Revision ID: 4ab8354e1ef2
Revises: None
Create Date: 2026-08-06

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4ab8354e1ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_run',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('crawler_version', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandate',
    sa.Column('mandate_type', sa.Enum('CONSTITUTIONAL_PERIOD', 'INSTITUTIONAL_PERIOD', 'OTHER', name='mandate_type', native_enum=False, length=48), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('end_condition_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_release',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('organization',
    sa.Column('preferred_name', sa.String(length=400), nullable=False),
    sa.Column('name_normalized', sa.String(length=400), nullable=False),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('public_private_category', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_preferred_name'), ['preferred_name'], unique=False)

    op.create_table('person',
    sa.Column('preferred_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_preferred_name'), ['preferred_name'], unique=False)

    op.create_table('review_task',
    sa.Column('task_type', sa.Enum('ENTITY_RESOLUTION', 'EFFECTIVE_DATE_UNSTATED', 'LINK_AFFECTED_ASSIGNMENT', 'POSITION_ORG_UNRESOLVED', 'ORG_VARIANT_CHECK', 'ONTOLOGY_CANDIDATE', 'EXTRACTION_CONFLICT', name='review_task_type', native_enum=False, length=48), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSED', name='review_task_status', native_enum=False, length=48), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_task_target_id'), ['target_id'], unique=False)

    op.create_table('source_system',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('source_family', sa.String(length=100), nullable=False),
    sa.Column('policy_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('source_system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_system_source_family'), ['source_family'], unique=False)

    op.create_table('organizational_unit',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('parent_unit_id', sa.String(length=32), nullable=True),
    sa.Column('preferred_name', sa.String(length=400), nullable=False),
    sa.Column('name_normalized', sa.String(length=400), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['organizational_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'parent_unit_id', 'name_normalized')
    )
    with op.batch_alter_table('organizational_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizational_unit_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizational_unit_organization_id'), ['organization_id'], unique=False)

    op.create_table('publication_issue',
    sa.Column('source_system_id', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('ordinary_or_extraordinary', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'issue_code')
    )
    with op.batch_alter_table('publication_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_issue_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_issue_source_system_id'), ['source_system_id'], unique=False)

    op.create_table('review_decision',
    sa.Column('review_task_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('ACCEPT', 'REJECT', 'LINK_ENTITY', 'CREATE_ENTITY', 'SPLIT_ENTITY', 'MARK_DATE_NOT_STATED', 'RESOLVE_POSITION', 'DISMISS', name='decision_action', native_enum=False, length=48), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decision_review_task_id'), ['review_task_id'], unique=False)

    op.create_table('position',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('organizational_unit_id', sa.String(length=32), nullable=True),
    sa.Column('preferred_label', sa.String(length=500), nullable=False),
    sa.Column('label_normalized', sa.String(length=500), nullable=False),
    sa.Column('position_type', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['organizational_unit_id'], ['organizational_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index('ix_position_identity', ['organization_id', 'organizational_unit_id', 'label_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_label_normalized'), ['label_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_organization_id'), ['organization_id'], unique=False)

    op.create_table('publication_item',
    sa.Column('issue_id', sa.String(length=32), nullable=True),
    sa.Column('source_series', sa.String(length=20), nullable=False),
    sa.Column('publication_code', sa.String(length=50), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['publication_issue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_series', 'publication_code')
    )
    with op.batch_alter_table('publication_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_item_publication_code'), ['publication_code'], unique=False)

    op.create_table('artifact',
    sa.Column('publication_item_id', sa.String(length=32), nullable=False),
    sa.Column('representation_type', sa.Enum('HTML', 'PDF', 'ISSUE_PDF', 'IMAGE', name='representation_type', native_enum=False, length=48), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['publication_item_id'], ['publication_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_item_id', 'representation_type')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_publication_item_id'), ['publication_item_id'], unique=False)

    op.create_table('artifact_version',
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=300), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('requested_url', sa.String(length=500), nullable=True),
    sa.Column('final_url', sa.String(length=500), nullable=True),
    sa.Column('object_key', sa.String(length=300), nullable=False),
    sa.Column('crawler_version', sa.String(length=100), nullable=True),
    sa.Column('previous_version_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('length(sha256) = 64', name='ck_artifact_version_sha256_len'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['artifact_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'sha256')
    )
    with op.batch_alter_table('artifact_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_version_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_version_sha256'), ['sha256'], unique=False)

    op.create_table('extraction_run',
    sa.Column('artifact_version_id', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('ontology_version', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='extraction_status', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_run_artifact_version_id'), ['artifact_version_id'], unique=False)

    op.create_table('legal_document',
    sa.Column('publication_item_id', sa.String(length=32), nullable=False),
    sa.Column('document_type_raw', sa.String(length=200), nullable=False),
    sa.Column('document_type_code', sa.Enum('RESOLUCION_MINISTERIAL', 'RESOLUCION_SUPREMA', 'RESOLUCION_JEFATURAL', 'RESOLUCION_DE_INTENDENCIA', 'RESOLUCION_DIRECTORAL', 'OTHER', name='document_type_code', native_enum=False, length=48), nullable=False),
    sa.Column('number_raw', sa.String(length=200), nullable=False),
    sa.Column('number_normalized', sa.String(length=200), nullable=False),
    sa.Column('title_raw', sa.Text(), nullable=False),
    sa.Column('issue_place_raw', sa.String(length=200), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('issuer_mention_id', sa.String(length=32), nullable=True),
    sa.Column('parsed_from_artifact_version_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issuer_mention_id'], ['organization_mention.id'], use_alter=True),
    sa.ForeignKeyConstraint(['parsed_from_artifact_version_id'], ['artifact_version.id'], ),
    sa.ForeignKeyConstraint(['publication_item_id'], ['publication_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_document_number_normalized'), ['number_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_document_publication_item_id'), ['publication_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_document_published_on'), ['published_on'], unique=False)

    op.create_table('document_section',
    sa.Column('legal_document_id', sa.String(length=32), nullable=False),
    sa.Column('section_type', sa.Enum('SUMMARY', 'DOC_TYPE', 'DOC_NUMBER', 'ISSUE_LINE', 'VISTOS', 'CONSIDERANDO', 'RESOLVE_HEADER', 'ARTICLE', 'ARTICLE_LIST_ITEM', 'CLOSING', 'SIGNATURE', 'PUBLICATION_CODE', 'ANNEX', 'OTHER', name='section_type', native_enum=False, length=48), nullable=False),
    sa.Column('label_raw', sa.String(length=200), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('text_normalized', sa.Text(), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_document_id', 'order_index')
    )
    with op.batch_alter_table('document_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_section_legal_document_id'), ['legal_document_id'], unique=False)
        batch_op.create_index('ix_document_section_type', ['legal_document_id', 'section_type'], unique=False)

    op.create_table('position_slot',
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.Column('external_scheme', sa.String(length=100), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'external_scheme', 'external_code')
    )
    with op.batch_alter_table('position_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_slot_position_id'), ['position_id'], unique=False)

    op.create_table('evidence_span',
    sa.Column('document_section_id', sa.String(length=32), nullable=True),
    sa.Column('artifact_version_id', sa.String(length=32), nullable=False),
    sa.Column('article_label', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('quoted_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('locator_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('length(quoted_text) > 0', name='ck_evidence_span_quote_nonempty'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.id'], ),
    sa.ForeignKeyConstraint(['document_section_id'], ['document_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_span', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_span_artifact_version_id'), ['artifact_version_id'], unique=False)

    op.create_table('assertion',
    sa.Column('extraction_run_id', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('object_value_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_span_id', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.Enum('CANDIDATE', 'AUTO_ACCEPTED', 'HUMAN_ACCEPTED', 'HUMAN_REJECTED', 'SUPERSEDED', name='review_status', native_enum=False, length=48), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('evidence_span_id IS NOT NULL', name='ck_assertion_requires_evidence'),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['assertion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assertion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assertion_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertion_predicate'), ['predicate'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertion_review_status'), ['review_status'], unique=False)
        batch_op.create_index('ix_assertion_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('document_reference',
    sa.Column('source_document_id', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.Enum('INTERNAL_SEEN_DOCUMENT', 'NORMATIVE_CITATION', 'PRIOR_APPOINTMENT', 'MODIFIES', 'REPEALS', 'CORRECTS', 'OTHER', name='reference_type', native_enum=False, length=48), nullable=False),
    sa.Column('target_document_id', sa.String(length=32), nullable=True),
    sa.Column('target_number_raw', sa.String(length=300), nullable=False),
    sa.Column('target_doc_kind_raw', sa.String(length=200), nullable=True),
    sa.Column('evidence_span_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['legal_document.id'], ),
    sa.ForeignKeyConstraint(['target_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_reference_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('organization_mention',
    sa.Column('legal_document_id', sa.String(length=32), nullable=True),
    sa.Column('text_raw', sa.String(length=500), nullable=False),
    sa.Column('text_normalized', sa.String(length=500), nullable=False),
    sa.Column('canonical_organization_id', sa.String(length=32), nullable=True),
    sa.Column('resolution_status', sa.Enum('UNRESOLVED', 'CANDIDATE_MATCH', 'AUTO_LINKED', 'HUMAN_CONFIRMED', 'HUMAN_REJECTED', 'MERGED', 'SPLIT', name='resolution_status', native_enum=False, length=48), nullable=False),
    sa.Column('evidence_span_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['canonical_organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], ),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_mention_text_normalized'), ['text_normalized'], unique=False)

    op.create_table('person_mention',
    sa.Column('legal_document_id', sa.String(length=32), nullable=False),
    sa.Column('text_raw', sa.String(length=400), nullable=False),
    sa.Column('text_normalized', sa.String(length=400), nullable=False),
    sa.Column('evidence_span_id', sa.String(length=32), nullable=False),
    sa.Column('canonical_person_id', sa.String(length=32), nullable=True),
    sa.Column('resolution_status', sa.Enum('UNRESOLVED', 'CANDIDATE_MATCH', 'AUTO_LINKED', 'HUMAN_CONFIRMED', 'HUMAN_REJECTED', 'MERGED', 'SPLIT', name='resolution_status', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['canonical_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], ),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_mention_canonical_person_id'), ['canonical_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_mention_legal_document_id'), ['legal_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_mention_text_normalized'), ['text_normalized'], unique=False)

    op.create_table('personnel_event',
    sa.Column('legal_document_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('DESIGNATION', 'APPOINTMENT', 'ACTING_ASSIGNMENT', 'ADDITIONAL_RESPONSIBILITY', 'ACCEPT_RESIGNATION', 'END_DESIGNATION', 'END_ACTING_ASSIGNMENT', 'TERMINATION', 'DELEGATION', 'OTHER_PERSONNEL_ACTION', name='event_type', native_enum=False, length=48), nullable=False),
    sa.Column('assignment_effect', sa.Enum('START', 'END', 'MODIFY', 'NONE', name='assignment_effect', native_enum=False, length=48), nullable=False),
    sa.Column('legal_verb_raw', sa.String(length=200), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_from_status', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'NOT_STATED', 'CONDITIONAL', name='date_status', native_enum=False, length=48), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('effective_to_status', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'NOT_STATED', 'CONDITIONAL', name='date_status_to', native_enum=False, length=48), nullable=False),
    sa.Column('end_condition_text', sa.Text(), nullable=True),
    sa.Column('collective_event_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_span_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collective_event_id'], ['personnel_event.id'], ),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], ),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personnel_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personnel_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_event_legal_document_id'), ['legal_document_id'], unique=False)

    op.create_table('event_participant',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('person_mention_id', sa.String(length=32), nullable=True),
    sa.Column('organization_mention_id', sa.String(length=32), nullable=True),
    sa.Column('role_in_event', sa.Enum('APPOINTEE', 'RESIGNING_PERSON', 'AFFECTED_PERSON', 'AFFECTED_PERSON_RECITAL_CANDIDATE', 'RETURNING_HOLDER', 'ISSUING_ORGANIZATION', name='participant_role', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['personnel_event.id'], ),
    sa.ForeignKeyConstraint(['organization_mention_id'], ['organization_mention.id'], ),
    sa.ForeignKeyConstraint(['person_mention_id'], ['person_mention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participant_event_id'), ['event_id'], unique=False)

    op.create_table('role_assignment',
    sa.Column('person_id', sa.String(length=32), nullable=True),
    sa.Column('person_mention_id', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=True),
    sa.Column('position_label_raw', sa.String(length=600), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('organization_path_raw', sa.Text(), nullable=True),
    sa.Column('assignment_kind', sa.Enum('TITULAR', 'ACTING', 'TEMPORARY', 'ADDITIONAL_RESPONSIBILITY', 'BOARD_MEMBERSHIP', 'UNKNOWN', name='assignment_kind', native_enum=False, length=48), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_from_status', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'NOT_STATED', 'CONDITIONAL', name='assignment_from_status', native_enum=False, length=48), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('valid_to_status', sa.Enum('EXPLICIT', 'DERIVED', 'INFERRED', 'NOT_STATED', 'CONDITIONAL', name='assignment_to_status', native_enum=False, length=48), nullable=False),
    sa.Column('end_condition_text', sa.Text(), nullable=True),
    sa.Column('start_event_id', sa.String(length=32), nullable=True),
    sa.Column('end_event_id', sa.String(length=32), nullable=True),
    sa.Column('mandate_id', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['end_event_id'], ['personnel_event.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_mention_id'], ['person_mention.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['start_event_id'], ['personnel_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_assignment_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_assignment_position_id'), ['position_id'], unique=False)

    op.create_table('signatory',
    sa.Column('legal_document_id', sa.String(length=32), nullable=False),
    sa.Column('person_mention_id', sa.String(length=32), nullable=False),
    sa.Column('capacity_raw', sa.String(length=400), nullable=True),
    sa.Column('organization_mention_id', sa.String(length=32), nullable=True),
    sa.Column('signature_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_document.id'], ),
    sa.ForeignKeyConstraint(['organization_mention_id'], ['organization_mention.id'], ),
    sa.ForeignKeyConstraint(['person_mention_id'], ['person_mention.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_document_id', 'signature_order')
    )
    with op.batch_alter_table('signatory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatory_legal_document_id'), ['legal_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signatory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatory_legal_document_id'))

    op.drop_table('signatory')
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_assignment_position_id'))
        batch_op.drop_index(batch_op.f('ix_role_assignment_person_id'))

    op.drop_table('role_assignment')
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participant_event_id'))

    op.drop_table('event_participant')
    with op.batch_alter_table('personnel_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personnel_event_legal_document_id'))
        batch_op.drop_index(batch_op.f('ix_personnel_event_event_type'))

    op.drop_table('personnel_event')
    with op.batch_alter_table('person_mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_mention_text_normalized'))
        batch_op.drop_index(batch_op.f('ix_person_mention_legal_document_id'))
        batch_op.drop_index(batch_op.f('ix_person_mention_canonical_person_id'))

    op.drop_table('person_mention')
    with op.batch_alter_table('organization_mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_mention_text_normalized'))

    op.drop_table('organization_mention')
    with op.batch_alter_table('document_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_reference_source_document_id'))

    op.drop_table('document_reference')
    with op.batch_alter_table('assertion', schema=None) as batch_op:
        batch_op.drop_index('ix_assertion_subject')
        batch_op.drop_index(batch_op.f('ix_assertion_review_status'))
        batch_op.drop_index(batch_op.f('ix_assertion_predicate'))
        batch_op.drop_index(batch_op.f('ix_assertion_extraction_run_id'))

    op.drop_table('assertion')
    with op.batch_alter_table('evidence_span', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_span_artifact_version_id'))

    op.drop_table('evidence_span')
    with op.batch_alter_table('position_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_slot_position_id'))

    op.drop_table('position_slot')
    with op.batch_alter_table('document_section', schema=None) as batch_op:
        batch_op.drop_index('ix_document_section_type')
        batch_op.drop_index(batch_op.f('ix_document_section_legal_document_id'))

    op.drop_table('document_section')
    with op.batch_alter_table('legal_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_document_published_on'))
        batch_op.drop_index(batch_op.f('ix_legal_document_publication_item_id'))
        batch_op.drop_index(batch_op.f('ix_legal_document_number_normalized'))

    op.drop_table('legal_document')
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_run_artifact_version_id'))

    op.drop_table('extraction_run')
    with op.batch_alter_table('artifact_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_version_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_version_artifact_id'))

    op.drop_table('artifact_version')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_publication_item_id'))

    op.drop_table('artifact')
    with op.batch_alter_table('publication_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_item_publication_code'))

    op.drop_table('publication_item')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_organization_id'))
        batch_op.drop_index(batch_op.f('ix_position_label_normalized'))
        batch_op.drop_index('ix_position_identity')

    op.drop_table('position')
    with op.batch_alter_table('review_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decision_review_task_id'))

    op.drop_table('review_decision')
    with op.batch_alter_table('publication_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_issue_source_system_id'))
        batch_op.drop_index(batch_op.f('ix_publication_issue_publication_date'))

    op.drop_table('publication_issue')
    with op.batch_alter_table('organizational_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizational_unit_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organizational_unit_name_normalized'))

    op.drop_table('organizational_unit')
    with op.batch_alter_table('source_system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_system_source_family'))

    op.drop_table('source_system')
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_task_target_id'))
        batch_op.drop_index(batch_op.f('ix_review_task_status'))

    op.drop_table('review_task')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_preferred_name'))

    op.drop_table('person')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_preferred_name'))
        batch_op.drop_index(batch_op.f('ix_organization_name_normalized'))

    op.drop_table('organization')
    op.drop_table('ontology_release')
    op.drop_table('mandate')
    op.drop_table('crawl_run')
    # ### end Alembic commands ###
